### ISSUE TITLE
Docker-Missing entrypoint.sh

### ISSUE THREAD

**Issue by y0himba** [lkwq007/stablediffusion-infinity#33]
Hello.

I am brand new to Docker, and this is my first attempt at using it.  

I am on Windows 10, admin command prompt. 

I have run the commands as shown under the install directions. The first two command work, however, I am getting the following error when I try to 'compose up':
```
C:\stable-diffusion\stablediffusion-infinity>docker-compose up
[+] Running 4/4
 - Network stablediffusion-infinity_default          Created                                                       0.1s
 - Volume "stablediffusion-infinity_cond_env"        Created                                                       0.0s
 - Volume "stablediffusion-infinity_user_home"       Created                                                       0.0s
 - Container stablediffusion-infinity-sd-infinity-1  Created                                                       0.2s
Attaching to stablediffusion-infinity-sd-infinity-1
stablediffusion-infinity-sd-infinity-1  | exec /home/user/app/docker/entrypoint.sh: no such file or directory
stablediffusion-infinity-sd-infinity-1 exited with code 1
```
What information can I give to help troubleshoot? Since I am on Win10, I am having issues locating the directories in the WSL system. To be honest, I am not even sure I am using the right words to describe the above sentence. 

Any help is welcome.

**Comment by throttlekitty** [comment]
Also win 10, same issue.

I used this command to enter the docker image, and found that home/user/app/ is empty.
docker run -it --rm --entrypoint=bash outpaint1-stablediffusion-infinity-sd-infinity

But I'm not familiar with docker at all, so I'm not sure where to go from there. Some searching on this issue says that text encoding on the docker files is the issue, but I see that these are already encoded in UTF-8, which should work on windows.

**Comment by SkyeErnst** [comment]
I also have the same problem, and am running windows 10.

Interestingly, I tried downloading the repo as a zip file rather than cloning it and I'm able to get farther with the install, however I still run into trouble. fpie fails to install with the following output:

```
Running setup.py install for fpie: started
stablediffusion-infinity-master-sd-infinity-1 |   Running setup.py install for fpie: finished with status 'error'
stablediffusion-infinity-master-sd-infinity-1 | 
stablediffusion-infinity-master-sd-infinity-1 | Pip subprocess error:
stablediffusion-infinity-master-sd-infinity-1 |   error: subprocess-exited-with-error
stablediffusion-infinity-master-sd-infinity-1 |   
stablediffusion-infinity-master-sd-infinity-1 |   × python setup.py bdist_wheel did not run successfully.
stablediffusion-infinity-master-sd-infinity-1 |   │ exit code: 1
stablediffusion-infinity-master-sd-infinity-1 |   ╰─> [17 lines of output]
stablediffusion-infinity-master-sd-infinity-1 |       running bdist_wheel
stablediffusion-infinity-master-sd-infinity-1 |       running build
stablediffusion-infinity-master-sd-infinity-1 |       running build_py
stablediffusion-infinity-master-sd-infinity-1 |       creating build
stablediffusion-infinity-master-sd-infinity-1 |       creating build/lib.linux-x86_64-cpython-310
stablediffusion-infinity-master-sd-infinity-1 |       creating build/lib.linux-x86_64-cpython-310/fpie
stablediffusion-infinity-master-sd-infinity-1 |       copying fpie/numba_solver.py -> build/lib.linux-x86_64-cpython-310/fpie
stablediffusion-infinity-master-sd-infinity-1 |       copying fpie/gui.py -> build/lib.linux-x86_64-cpython-310/fpie
stablediffusion-infinity-master-sd-infinity-1 |       copying fpie/np_solver.py -> build/lib.linux-x86_64-cpython-310/fpie
stablediffusion-infinity-master-sd-infinity-1 |       copying fpie/cli.py -> build/lib.linux-x86_64-cpython-310/fpie
stablediffusion-infinity-master-sd-infinity-1 |       copying fpie/taichi_solver.py -> build/lib.linux-x86_64-cpython-310/fpie
stablediffusion-infinity-master-sd-infinity-1 |       copying fpie/process.py -> build/lib.linux-x86_64-cpython-310/fpie
stablediffusion-infinity-master-sd-infinity-1 |       copying fpie/args.py -> build/lib.linux-x86_64-cpython-310/fpie
stablediffusion-infinity-master-sd-infinity-1 |       copying fpie/io.py -> build/lib.linux-x86_64-cpython-310/fpie
stablediffusion-infinity-master-sd-infinity-1 |       copying fpie/__init__.py -> build/lib.linux-x86_64-cpython-310/fpie
stablediffusion-infinity-master-sd-infinity-1 |       running build_ext
stablediffusion-infinity-master-sd-infinity-1 |       error: [Errno 2] No such file or directory: 'cmake'
stablediffusion-infinity-master-sd-infinity-1 |       [end of output
```

I tried installing cmake and running the container again, but I get the same output still.

**Comment by tpsjr7** [comment]
Once this PR is merged, those issues should be fixed: https://github.com/lkwq007/stablediffusion-infinity/pull/49

**Comment by SkyeErnst** [comment]
I'm still having trouble getting docker to run, though its a different problem now. After running the "docker-compose up" command, I get a very long output that ends with this:
```
stablediffusion-infinity-sd-infinity-1 | + python app.py --port=8888 --host=0.0.0.0
stablediffusion-infinity-sd-infinity-1 | OMP: Error #179: Function Can't open SHM2 failed:
stablediffusion-infinity-sd-infinity-1 | OMP: System error #2: No such file or directory
stablediffusion-infinity-sd-infinity-1 | /app/docker/entrypoint.sh: line 32:    84 Aborted                 python app.py --port=8888 --host=0.0.0.0
```
Any thoughts? This is my first time using docker and WSL, so its possible I messed something up but I'm not sure what it'd be.

In case its needed, the full terminal output is below, and I get this output either when I try to start the docker container or run the above mentioned command:
```
stablediffusion-infinity-sd-infinity-1 | + set -x
stablediffusion-infinity-sd-infinity-1 | + git submodule init
stablediffusion-infinity-sd-infinity-1 | + git submodule update
stablediffusion-infinity-sd-infinity-1 | + git config --global credential.helper store
stablediffusion-infinity-sd-infinity-1 | + conda env list
stablediffusion-infinity-sd-infinity-1 | + grep sd-inf
stablediffusion-infinity-sd-infinity-1 | sd-inf                   /home/user/.conda/envs/sd-inf
stablediffusion-infinity-sd-infinity-1 | + . /opt/conda/etc/profile.d/conda.sh
stablediffusion-infinity-sd-infinity-1 | ++ export CONDA_EXE=/opt/conda/bin/conda
stablediffusion-infinity-sd-infinity-1 | ++ CONDA_EXE=/opt/conda/bin/conda
stablediffusion-infinity-sd-infinity-1 | ++ export _CE_M=
stablediffusion-infinity-sd-infinity-1 | ++ _CE_M=
stablediffusion-infinity-sd-infinity-1 | ++ export _CE_CONDA=
stablediffusion-infinity-sd-infinity-1 | ++ _CE_CONDA=
stablediffusion-infinity-sd-infinity-1 | ++ export CONDA_PYTHON_EXE=/opt/conda/bin/python
stablediffusion-infinity-sd-infinity-1 | ++ CONDA_PYTHON_EXE=/opt/conda/bin/python
stablediffusion-infinity-sd-infinity-1 | ++ '[' -z '' ']'
stablediffusion-infinity-sd-infinity-1 | ++ export CONDA_SHLVL=0
stablediffusion-infinity-sd-infinity-1 | ++ CONDA_SHLVL=0
stablediffusion-infinity-sd-infinity-1 | ++ '[' -n '' ']'
stablediffusion-infinity-sd-infinity-1 | ++++ dirname /opt/conda/bin/conda
stablediffusion-infinity-sd-infinity-1 | +++ dirname /opt/conda/bin
stablediffusion-infinity-sd-infinity-1 | ++ PATH=/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
stablediffusion-infinity-sd-infinity-1 | ++ export PATH
stablediffusion-infinity-sd-infinity-1 | ++ '[' -z '' ']'
stablediffusion-infinity-sd-infinity-1 | ++ PS1=
stablediffusion-infinity-sd-infinity-1 | + conda activate sd-inf
stablediffusion-infinity-sd-infinity-1 | + local cmd=activate
stablediffusion-infinity-sd-infinity-1 | + case "$cmd" in
stablediffusion-infinity-sd-infinity-1 | + __conda_activate activate sd-inf
stablediffusion-infinity-sd-infinity-1 | + '[' -n '' ']'
stablediffusion-infinity-sd-infinity-1 | + local ask_conda
stablediffusion-infinity-sd-infinity-1 | ++ PS1=
stablediffusion-infinity-sd-infinity-1 | ++ __conda_exe shell.posix activate sd-inf
stablediffusion-infinity-sd-infinity-1 | ++ __add_sys_prefix_to_path
stablediffusion-infinity-sd-infinity-1 | ++ '[' -n '' ']'
stablediffusion-infinity-sd-infinity-1 | +++ dirname /opt/conda/bin/conda
stablediffusion-infinity-sd-infinity-1 | ++ SYSP=/opt/conda/bin
stablediffusion-infinity-sd-infinity-1 | +++ dirname /opt/conda/bin
stablediffusion-infinity-sd-infinity-1 | ++ SYSP=/opt/conda
stablediffusion-infinity-sd-infinity-1 | ++ '[' -n '' ']'
stablediffusion-infinity-sd-infinity-1 | ++ PATH=/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
stablediffusion-infinity-sd-infinity-1 | ++ export PATH
stablediffusion-infinity-sd-infinity-1 | ++ /opt/conda/bin/conda shell.posix activate sd-inf
stablediffusion-infinity-sd-infinity-1 | + ask_conda='PS1='\''(sd-inf) '\''
stablediffusion-infinity-sd-infinity-1 | export PATH='\''/home/user/.conda/envs/sd-inf/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'\''
stablediffusion-infinity-sd-infinity-1 | export CONDA_PREFIX='\''/home/user/.conda/envs/sd-inf'\''
stablediffusion-infinity-sd-infinity-1 | export CONDA_SHLVL='\''1'\''
stablediffusion-infinity-sd-infinity-1 | export CONDA_DEFAULT_ENV='\''sd-inf'\''
stablediffusion-infinity-sd-infinity-1 | export CONDA_PROMPT_MODIFIER='\''(sd-inf) '\''
stablediffusion-infinity-sd-infinity-1 | export CONDA_EXE='\''/opt/conda/bin/conda'\''
stablediffusion-infinity-sd-infinity-1 | export _CE_M='\'''\''
stablediffusion-infinity-sd-infinity-1 | export _CE_CONDA='\'''\''
stablediffusion-infinity-sd-infinity-1 | export CONDA_PYTHON_EXE='\''/opt/conda/bin/python'\'''
stablediffusion-infinity-sd-infinity-1 | + eval 'PS1='\''(sd-inf) '\''
stablediffusion-infinity-sd-infinity-1 | export PATH='\''/home/user/.conda/envs/sd-inf/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'\''
stablediffusion-infinity-sd-infinity-1 | export CONDA_PREFIX='\''/home/user/.conda/envs/sd-inf'\''
stablediffusion-infinity-sd-infinity-1 | export CONDA_SHLVL='\''1'\''
stablediffusion-infinity-sd-infinity-1 | export CONDA_DEFAULT_ENV='\''sd-inf'\''
stablediffusion-infinity-sd-infinity-1 | export CONDA_PROMPT_MODIFIER='\''(sd-inf) '\''
stablediffusion-infinity-sd-infinity-1 | export CONDA_EXE='\''/opt/conda/bin/conda'\''
stablediffusion-infinity-sd-infinity-1 | export _CE_M='\'''\''
stablediffusion-infinity-sd-infinity-1 | export _CE_CONDA='\'''\''
stablediffusion-infinity-sd-infinity-1 | export CONDA_PYTHON_EXE='\''/opt/conda/bin/python'\'''
stablediffusion-infinity-sd-infinity-1 | ++ PS1='(sd-inf) '
stablediffusion-infinity-sd-infinity-1 | ++ export PATH=/home/user/.conda/envs/sd-inf/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
stablediffusion-infinity-sd-infinity-1 | ++ PATH=/home/user/.conda/envs/sd-inf/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
stablediffusion-infinity-sd-infinity-1 | ++ export CONDA_PREFIX=/home/user/.conda/envs/sd-inf
stablediffusion-infinity-sd-infinity-1 | ++ CONDA_PREFIX=/home/user/.conda/envs/sd-inf
stablediffusion-infinity-sd-infinity-1 | ++ export CONDA_SHLVL=1
stablediffusion-infinity-sd-infinity-1 | ++ CONDA_SHLVL=1
stablediffusion-infinity-sd-infinity-1 | ++ export CONDA_DEFAULT_ENV=sd-inf
stablediffusion-infinity-sd-infinity-1 | ++ CONDA_DEFAULT_ENV=sd-inf
stablediffusion-infinity-sd-infinity-1 | ++ export 'CONDA_PROMPT_MODIFIER=(sd-inf) '
stablediffusion-infinity-sd-infinity-1 | ++ CONDA_PROMPT_MODIFIER='(sd-inf) '
stablediffusion-infinity-sd-infinity-1 | ++ export CONDA_EXE=/opt/conda/bin/conda
stablediffusion-infinity-sd-infinity-1 | ++ CONDA_EXE=/opt/conda/bin/conda
stablediffusion-infinity-sd-infinity-1 | ++ export _CE_M=
stablediffusion-infinity-sd-infinity-1 | ++ _CE_M=
stablediffusion-infinity-sd-infinity-1 | ++ export _CE_CONDA=
stablediffusion-infinity-sd-infinity-1 | ++ _CE_CONDA=
stablediffusion-infinity-sd-infinity-1 | ++ export CONDA_PYTHON_EXE=/opt/conda/bin/python
stablediffusion-infinity-sd-infinity-1 | ++ CONDA_PYTHON_EXE=/opt/conda/bin/python
stablediffusion-infinity-sd-infinity-1 | + __conda_hashr
stablediffusion-infinity-sd-infinity-1 | + '[' -n '' ']'
stablediffusion-infinity-sd-infinity-1 | + '[' -n '' ']'
stablediffusion-infinity-sd-infinity-1 | + hash -r
stablediffusion-infinity-sd-infinity-1 | + shasum -c /home/user/.environment.sha
stablediffusion-infinity-sd-infinity-1 | + echo 'environment.yml is unchanged.'
stablediffusion-infinity-sd-infinity-1 | environment.yml is unchanged.
stablediffusion-infinity-sd-infinity-1 | + python app.py --port=8888 --host=0.0.0.0
stablediffusion-infinity-sd-infinity-1 | OMP: Error #179: Function Can't open SHM2 failed:
stablediffusion-infinity-sd-infinity-1 | OMP: System error #2: No such file or directory
stablediffusion-infinity-sd-infinity-1 | /app/docker/entrypoint.sh: line 32:    84 Aborted                 python app.py --port=8888 --host=0.0.0.0

```

**Comment by tpsjr7** [comment]
Haven't seen that one with OMP errors. Can you double check if you run this command from your shell, do you see your GPU listed?

`docker run -it --gpus=all --rm nvidia/cuda:11.4.2-base-ubuntu20.04 nvidia-smi`

**Comment by tpsjr7** [comment]
I'm guessing, seeing that the error is saying, "OMP:" I see that the requirements are pulling in intel-openmp. Do you have an Intel CPU? If not, maybe why that's failing. Also another guess, maybe it's failing here, https://github.com/lkwq007/stablediffusion-infinity/blob/a2afeb89fa8fc4c4dfa88bedca159ebbc64edb32/process.py#L61 

Can you try commenting out or deleting that try block in process.py that's trying to use openmp? maybe the code will fall back to using another backend instead of failing there.

```
## DELETE ME
try:
  from fpie import core_openmp  # type: ignore
  DEFAULT_BACKEND = "openmp"
  ALL_BACKEND.append("openmp")
except ImportError:
  core_openmp = None
```

**Comment by throttlekitty** [comment]
Thanks tpsjr7, however I'm still having issues after updating. docker-compose build runs successfully. docker-compose up returns this:

```
[+] Running 2/2
 - Network outpaint1-stablediffusion-infinity_default          Created                                             0.7s
 - Container outpaint1-stablediffusion-infinity-sd-infinity-1  Created                                             0.1s
Attaching to outpaint1-stablediffusion-infinity-sd-infinity-1
outpaint1-stablediffusion-infinity-sd-infinity-1  | exec /app/docker/entrypoint.sh: no such file or directory
outpaint1-stablediffusion-infinity-sd-infinity-1 exited with code 1
```

**Comment by JeromeFr** [comment]
@tpsjr7 I have an AMD Ryzen so it could be that indeed. I'll have a look if there is any equivalent to intel-openmp for AMD or if I need to comment out something. Thanks !

**Comment by throttlekitty** [comment]
> 

Oh, I didn't even check today, assuming nothing changed for me. Yeah, that file exists, app/ is totally populated now, it was empty before your change. So i tried running it manually, like so:

```
(sd-inf) E:\stable-diffusion\outpaint1-stablediffusion-infinity>docker-compose run sd-infinity bash
(base) user@3382a8b92a3c:/app$ cd docker
(base) user@3382a8b92a3c:/app/docker$ ls
Dockerfile  entrypoint.sh  opencv.pc  run-shell.sh
(base) user@3382a8b92a3c:/app/docker$ exec entrypoint.sh
bash: exec: entrypoint.sh: not found
```

**Comment by tpsjr7** [comment]
I'd clear, update, and delete everything and try again
```
git pull
docker-compose down
docker-compose build
docker-compose up
```

**Comment by throttlekitty** [comment]
done, and same result still.

**Comment by tpsjr7** [comment]
"(sd-inf) E:\stable-diffusion\outpaint1-stablediffusion-infinity"

Are you running docker from the windows command prompt? 

I run using the Ubuntu commandline from the microsoft store https://www.microsoft.com/store/productId/9MTTCL66CPXJ

`$ uname -a 
Linux DESKTOP-7UA648I 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

`$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
`

**Comment by Miro88cz** [comment]
You don't have any WSL 2 distro. Please convert a WSL 1 distro to WSL 2, or install a new distro and it will appear here.

**Comment by throttlekitty** [comment]
> Are you running docker from the windows command prompt? That does not work for me, I run into that OMP error.

I've tried it in an windows cmd as admin, as well as the miniconda console. WSL Integration is checked, but also says "You don't have any WSL 2 distro. Please convert a WSL 1 distro to WSL 2, or install a new distro and it will appear here."

Not too interested in installing Ubuntu for this, but thanks for the help all the same!

**Comment by Miro88cz** [comment]
the same but thanks

(base) C:\AI-New\infinity\stablediffusion-infinity-1\docker>docker-compose run sd-infinity bash
(base) user@b7540ea6e847:/app$ cd docker
(base) user@b7540ea6e847:/app/docker$ ls
Dockerfile  entrypoint.sh  opencv.pc  run-shell.sh
(base) user@b7540ea6e847:/app/docker$ exec entrypoint.sh
bash: exec: entrypoint.sh: not found
(base) user@b7540ea6e847:/app/docker$

**Comment by tpsjr7** [comment]
```
(sd-inf) user@7fde8000417a:/app/docker$ exec entrypoint.sh
bash: exec: entrypoint.sh: not found
``` 
Does not work. 

This should work:
```
(sd-inf) user@7fde8000417a:/app/docker$ ./entrypoint.sh
```

**Comment by Miro88cz** [comment]
how to cd in ubuntu?
XXXX:~$ C:\AI-New\infinity\stablediffusion-infinity-1\docker>docker-compose run sd-infinty bash
C:AI-Newinfinitystablediffusion-infinity-1docker: command not found

**Comment by JeromeFr** [comment]
@Miro88cz your C drive would be mounted under /mnt/
try `cd /mnt/c/AI-New/infinity/stablediffusion-infinity-1/docker`

**Comment by JeromeFr** [comment]
> 

@tpsjr7 : I was running it from Windows Terminal which uses Powershell 7 on my machine. I tried with ubuntu as suggested in post https://github.com/lkwq007/stablediffusion-infinity/issues/33#issuecomment-1268790151 but I'm struggling with it. How did you run docker-compose build and docker-compose up? As your unix user or as root?

If I use it as my unix user, I got this error message :
```
unixusr@DESKTOP-4GPKQJ3:/mnt/e/stablediffusion/stablediffusion-infinity$ docker-compose build
[+] Building 0.0s (0/0)
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/version": dial unix /var/run/docker.sock: connect: permission denied: driver not connecting
```

If I use `sudo docker-compose build` it passes but then `sudo docker-compose up` throws this error : 
```
unixusr@DESKTOP-4GPKQJ3:/mnt/e/stablediffusion/stablediffusion-infinity$ sudo docker-compose up
Creating network "stablediffusion-infinity_default" with the default driver
Creating stablediffusion-infinity_sd-infinity_1 ... done
Attaching to stablediffusion-infinity_sd-infinity_1
sd-infinity_1  | + set -x
sd-infinity_1  | + git submodule init
sd-infinity_1  | + git submodule update
sd-infinity_1  | error: chmod on /app/.git/modules/PyPatchMatch/config.lock failed: Operation not permitted
sd-infinity_1  | fatal: could not set 'core.worktree' to '../../../PyPatchMatch'
stablediffusion-infinity_sd-infinity_1 exited with code 1
```

I was expecting a chmod to be permitted as root

**Comment by SkyeErnst** [comment]
Trying to run the docker commands in a WSL2 ubuntu terminal now, and I get this error when running the first docker command
```
skye@SkyePC:/mnt/f/_PROGRAMING/Notebooks/_Docker/stablediffusion-infinity$ sudo docker-compose build
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
```

**Comment by tpsjr7** [comment]
You can try changing the version from 3.9 to 3.3  in the docker-compose.yml, it works for me.

Also I'm using
```
$ docker-compose -v
Docker Compose version v2.10.2

$ docker version

Server: Docker Desktop
 Engine:
  Version:          20.10.17
```

**Comment by SkyeErnst** [comment]
@tpsjr7 I did try changing the version in .yml file, and ran into other issues. Though I think I might know what part of the problem is now, my docker-compose version is 1.29.2. I couldn't update the package though, either through apt-get or pip. Both seem to think the latest version is 1.29.2, even though its clearly not. I had to download it off of their git repo, but the good news is its finally working. Thank you very much for the help!

**Comment by tpsjr7** [comment]
> Tried to docker compose in both powershell and CMD prompt with same results:

If you want to use docker, only these two options currently work:

- A native Linux environment with docker
- Windows using the Windows Ubuntu command line ( see https://github.com/lkwq007/stablediffusion-infinity/issues/33#issuecomment-1268847351 )

Things that don't work at the moment:
- running "docker-compose up" from CMD or Powershell or from anywhere else

**Comment by JeromeFr** [comment]
> I've updated the README on how to setup.

Thanks, I got it running now thanks to docker-run.sh .
I'm grateful for all your help
